apiVersion: v1
kind: ConfigMap
metadata:
  name: aerofusionxr-config
  namespace: aerofusionxr
  labels:
    app: aerofusionxr
    component: config
data:
  # Database Configuration
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "aerofusionxr"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Service Discovery
  API_GATEWAY_URL: "http://api-gateway-service:8000"
  AI_CONCIERGE_URL: "http://ai-concierge-service:8001"
  WAYFINDING_URL: "http://wayfinding-service:8002"
  FLIGHT_INFO_URL: "http://flight-info-service:8003"
  BAGGAGE_TRACKER_URL: "http://baggage-tracker-service:8004"
  COMMERCE_URL: "http://commerce-service:8005"
  USER_PROFILE_URL: "http://user-profile-service:8006"
  NOTIFICATIONS_URL: "http://notifications-service:8007"
  RECOMMENDATIONS_URL: "http://recommendations-service:8008"
  
  # Monitoring & Observability
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger-collector:14268/api/traces"
  PROMETHEUS_ENDPOINT: "http://prometheus-service:9090"
  GRAFANA_ENDPOINT: "http://grafana-service:3000"
  
  # Security
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRY_HOURS: "24"
  RATE_LIMIT_REQUESTS: "1000"
  RATE_LIMIT_WINDOW: "3600"
  
  # Performance
  CACHE_TTL: "300"
  REQUEST_TIMEOUT: "30"
  MAX_CONNECTIONS: "100"
  
  # Feature Flags
  ENABLE_BIOMETRIC_AUTH: "true"
  ENABLE_AR_FEATURES: "true"
  ENABLE_OFFLINE_MODE: "true"
  ENABLE_ANALYTICS: "true"
  
  # Environment
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aerofusionxr-nginx-config
  namespace: aerofusionxr
data:
  nginx.conf: |
    upstream api_gateway {
        server api-gateway-service:8000;
    }
    
    upstream ai_concierge {
        server ai-concierge-service:8001;
    }
    
    upstream wayfinding {
        server wayfinding-service:8002;
    }
    
    server {
        listen 80;
        server_name aerofusionxr.com;
        
        location /api/v1/ {
            proxy_pass http://api_gateway;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    } 