apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:

* ../charts/api-gateway
* ../charts/booking
* ../charts/wayfinding
* ../charts/ai-concierge

patchesStrategicMerge:

* overlays/\${ENV}/configmap.yaml
* overlays/\${ENV}/secrets.yaml
