apiVersion: v1
kind: ServiceAccount
metadata:
  name: aerofusionxr-service-account
  namespace: aerofusionxr
  labels:
    app: aerofusionxr
    component: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerofusionxr-cluster-role
  labels:
    app: aerofusionxr
    component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aerofusionxr-cluster-role-binding
  labels:
    app: aerofusionxr
    component: rbac
subjects:
- kind: ServiceAccount
  name: aerofusionxr-service-account
  namespace: aerofusionxr
roleRef:
  kind: ClusterRole
  name: aerofusionxr-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aerofusionxr-role
  namespace: aerofusionxr
  labels:
    app: aerofusionxr
    component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aerofusionxr-role-binding
  namespace: aerofusionxr
  labels:
    app: aerofusionxr
    component: rbac
subjects:
- kind: ServiceAccount
  name: aerofusionxr-service-account
  namespace: aerofusionxr
roleRef:
  kind: Role
  name: aerofusionxr-role
  apiGroup: rbac.authorization.k8s.io 