AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS Snapshot & Restore Blueprint for Legacy Databases'
Resources:
  LegacyDBSnapshot:
    Type: AWS::RDS::DBSnapshot
    Properties:
      DBInstanceIdentifier: !Ref LegacyDBInstance
      DBSnapshotIdentifier: !Sub "legacy-db-snapshot-${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"

  LegacyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: "legacy-db-instance"
      DBInstanceClass: db.t3.small
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      VPCSecurityGroups:
        - sg-0123456789abcdef0
      DBSubnetGroupName: default
      PubliclyAccessible: false

Parameters:
  DBUsername:
    Type: String
    NoEcho: true
    Description: 'Master DB username'
  DBPassword:
    Type: String
    NoEcho: true
    Description: 'Master DB password'

Outputs:
  SnapshotId:
    Description: 'Identifier of created DB snapshot'
    Value: !Ref LegacyDBSnapshot
  DBInstanceArn:
    Description: 'ARN of the Legacy DB Instance'
    Value: !GetAtt LegacyDBInstance.Arn
