receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  
  resourcedetection:
    detectors: [env, system]
    timeout: 2s
  
  attributes:
    actions:
      - key: environment
        value: ${ENV:production}
        action: insert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: aerofusion
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true
  
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    index: "traces"
  
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777
  
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [jaeger, elasticsearch, logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [prometheus, logging]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [elasticsearch, logging] 