global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'commerce-service'
    static_configs:
      - targets: ['commerce-service:3000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'flight-info-service'
    static_configs:
      - targets: ['flight-info-service:8000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 
