apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-info
  labels:
    app: flight-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-info
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flight-info
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: flight-info
        image: aerofusion/flight-info:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: flight-info-secrets
              key: mongo-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: flight-info-secrets
              key: redis-url
        - name: VENDOR1_API_KEY
          valueFrom:
            secretKeyRef:
              name: flight-info-secrets
              key: vendor1-api-key
        - name: VENDOR2_API_KEY
          valueFrom:
            secretKeyRef:
              name: flight-info-secrets
              key: vendor2-api-key
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: flight-info
  labels:
    app: flight-info
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: flight-info
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flight-info
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: flight-info.aerofusion.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flight-info
            port:
              name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flight-info
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flight-info
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
---
apiVersion: v1
kind: Secret
metadata:
  name: flight-info-secrets
type: Opaque
data:
  mongo-url: bW9uZ29kYjovL21vbmdvLWZsaWdodC1pbmZvOjI3MDE3L2ZsaWdodC1pbmZv # mongodb://mongo-flight-info:27017/flight-info
  redis-url: cmVkaXM6Ly9yZWRpcy1mbGlnaHQtaW5mbzo2Mzc5 # redis://redis-flight-info:6379
  vendor1-api-key: QUtJQVhYWFhYWFhYWFhYWFhYWA== # AKIAXXXXXXXXXXXX
  vendor2-api-key: eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eA== # xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 