name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit & Integration Tests
        run: npm test

      - name: Terraform fmt & validate
        working-directory: infra/terraform
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate

      - name: SAST Scan (Semgrep)
        uses: returntocorp/semgrep-action@v2
        with:
          config: auto

      - name: DAST Scan (OWASP ZAP)
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:3000'

      - name: Compliance Gates
        run: |
          scripts/check-policy-gates.sh
